#!/bin/bash
# Usage: script/vagrant-share
#
# A front-end script to run in order to share an HTTP session for your running
# vagrant box (handy for providing a web app link that’s served from your
# machine).
set -e

vagrant share --http 3000
